services:
  nuxt-app:
    build: .
    container_name: nuxt-app

    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NUXT_PORT=3000
    command: 'npm run dev'
    volumes:
      - ./:/nuxt-app
      - 'nuxtvm:/nuxt-app/node_modules'

volumes:
  nuxtvm: